// The weld: take the single-file HTML bundle Vite produced and freeze it into
// an F# source file holding the page as a [<Literal>] string, so the backend
// serves the UI straight from its own binary: no files, no fetches.
//
// Same step as WrenHello's scripts/weld.js (there the literal lands in a Clef
// binary's .rodata). Pipeline:
//   dotnet fable  ->  vite build (vite-plugin-singlefile)  ->  verify  ->  this
//
// Output path and module name are parameters, because the backend wiring is
// decided inside Bozzetto, not here. Default: dist/EmbeddedAssets.fs only.
//   node scripts/weld.js [--out <path>] [--module <F# module name>]
//   BOZZETTO_WEB_WELD_OUT / BOZZETTO_WEB_WELD_MODULE set the same.
// A backend that prefers an embedded resource can take dist/index.html as is.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function option(name, environment, fallback) {
  const index = process.argv.indexOf(name);
  if (index >= 0) {
    const value = process.argv[index + 1];
    if (!value || value.startsWith('--')) {
      console.error(`weld: ${name} needs a value`);
      process.exit(2);
    }
    return value;
  }
  return process.env[environment] || fallback;
}

const bundlePath = 'dist/index.html';
const outPath = resolve(option('--out', 'BOZZETTO_WEB_WELD_OUT', 'dist/EmbeddedAssets.fs'));
const moduleName = option('--module', 'BOZZETTO_WEB_WELD_MODULE', 'Bozzetto.Web.EmbeddedAssets');

if (!/^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/.test(moduleName)) {
  console.error(`weld: invalid module name ${moduleName}`);
  process.exit(2);
}

const html = readFileSync(bundlePath, 'utf8');

// The bundle is embedded as an F# triple-quoted string literal, which cannot
// itself contain a triple quote, nor end with a quote. Fail loudly rather
// than emit a source file that cannot parse.
if (html.includes('"""') || html.endsWith('"')) {
  console.error('weld: dist/index.html contains a triple quote or ends with a quote; cannot embed.');
  process.exit(1);
}

const source =
  '// GENERATED by bozzetto-web/scripts/weld.js; do not edit by hand.\n' +
  '// Run `npm run build` in bozzetto-web to regenerate from the Fable + Vite bundle.\n' +
  '//\n' +
  '// The complete browser UI (HTML, JS and CSS inlined by Vite) as one literal,\n' +
  '// served by the daemon from memory: no files, no fetches. [<Literal>] keeps\n' +
  '// the constant inlined at its use site, the form Composer also lowers.\n' +
  `module ${moduleName}\n` +
  '\n' +
  '[<Literal>]\n' +
  'let IndexHtml = """' + html + '"""\n';

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, source);
console.log(`weld: embedded ${bundlePath} (${(Buffer.byteLength(html) / 1024).toFixed(1)} KiB) -> ${outPath} as ${moduleName}.IndexHtml`);
